name: Deploy to Vercel

on:
  push:
    branches:
      - main  # 或者你的默认分支名称
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Run hook
        run: curl https://api.vercel.com/v1/integrations/deploy/prj_ROp0MAb6QkXYVninc3iwkTD8WNgK/2v4afU5Chv
